### ISSUE TITLE
[request] Support for mjml options

### ISSUE THREAD

**Issue by lachieh** [tdeNL/tde-webpack-mjml-plugin#15]
Thanks for the work on this. Love the plugin.

It would be good to be able to configure the [mjml options](https://documentation.mjml.io/#inside-node-js) through the plugin parameters. At the moment, the only option that is passed through is the `filePath`:

https://github.com/tdeNL/tde-webpack-mjml-plugin/blob/59618ffa6913e65a95422436c3adad69ecf1b286/src/webpack-mjml-store.js#L93-L95

It would be great to be able to pass the options to the plugin, or alternatively enable the `useMjmlConfigOptions` option so that then it would pick up the `config` property inside the root level `.mjmlconfig` file. This option is set to false by default.

If you're open to PRs, I can submit something.

**Comment by matteobertoldo** [comment]
@lachieh great idea! any updates: @jordikroon? 😊

**Comment by matteobertoldo** [comment]
@lachieh @jordikroon sample reference [here](https://github.com/webatvantage/webatvantage-webpack-mjml-plugin/commit/952cae07e179ed832ba30163c249a4e04066b635)

**Comment by jordikroon** [comment]
Hi @lachieh / @matteobertoldo

I am sorry that this issue is still open, and I would like to thank you for using this plugin.

Internally we aren't actively using MJML anymore and with that I regret to inform that we do not plan to maintain this plugin anymore. 

That said. We are willing to give access to this repository and NPM to those who would love to revive this Webpack plugin.

**Comment by matteobertoldo** [comment]
@jordikroon thanks for the information.

If you don't mind I'll create a new repo, with the options available, so a new `npm` package! 📦. I have other repositories to maintain and I would like to be able to maintain them independently.

Thanks again!

**Comment by jordikroon** [comment]
@matteobertoldo Feel free to create a fork of this repo. Once your package has been released I can mark this repo as abandoned and suggest the new (your) package in this repo if that is okay to you?

**Comment by jordikroon** [comment]
With forking, it is ok to remove/rename `tde-` from the package name.

**Comment by matteobertoldo** [comment]
@jordikroon ok dude! thank u so much! ❤️ I'll let you know as soon as it's ready, thanks again.

**Comment by matteobertoldo** [comment]
@jordikroon Hi dude! https://github.com/matteobertoldo/webpack-mjml-plugin fresh new package! 📦 with support for all MJML configurations! 🍿 

cheers! 😊 🍻

**Comment by lachieh** [comment]
Thanks to the @jordikroon and the @tdeNL team for building this plugin initially and offering it up for community support. Thanks to @matteobertoldo for taking over maintenance!

I don't use this plugin anymore either, but this was a great result and a reflection of how awesome the open-source community is.

Since @matteobertoldo's plugin covers the original issue, I'm going to close this issue.

Thanks, everyone! 💯
