### ISSUE TITLE
Path delimiters mismatch in Windows.

### ISSUE THREAD

**Issue by graycrow** [tdeNL/tde-webpack-mjml-plugin#7]
I'm using `path.resolve()` to generate paths for `inputPath` and `outputPath`. In unix-based OS output files are placed in the correct directory. In windows html files are generated in the same directory as input files.  

It happens because `path.resolve()` in Windows return path in Windows format, with backslash as delimiter, but `glob()` always returns paths with forward slash and `replace()` function cannot find a match then and output path stays the same. 

Maybe it's a good idea to normalize paths to the forward slash? For example like this
```
const WebpackMjmlStore = function (inputPath, options) {
    this.inputPath = inputPath.replace(/\\/g,"/");
    this.options = _.defaults(options, defaultOptions);
    this.options.outputPath = this.options.outputPath.replace(/\\/g,"/");
};
```

**Comment by jordikroon** [comment]
@graycrow This has just been released with 1.4.0!
