### ISSUE TITLE
Support for mj-include relative path.

### ISSUE THREAD

**Issue by graycrow** [tdeNL/tde-webpack-mjml-plugin#8]
This plugin doesn't work correctly when *mj-include* referencing a file with relative path, for example `<mj-include path="../includes/header.mjml" />`.

It can be fixed with creating optional `filePath` property on the mjml2html function options object.

So, maybe this plugin should make it possible? As another config parameter for example?
```
const defaultOptions = {
    extension: ".html",
    outputPath: "",
    filePath: "."
};

...

let response = mjml2html(contents, {
    filePath: that.options.filePath
});
```

**Comment by jordikroon** [comment]
Released with 1.4.0!
